version: "3.8"

services:
  app:

    build: .

    ports:
      - ${PORT}:${PORT}

    env_file: .env

    environment:
      DB_HOST: "postgres-db"

    depends_on:
      - db

    networks:
      - series-nw

  db:

    container_name: "postgres-db"

    image: "postgres:latest"

    ports:
      - ${DB_PORT}:5432

    volumes:
      - ${PG_VOLUME_PATH}:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB:   ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DATABASE_HOST: ${DB_HOST} 

    networks:
      - series-nw

networks:
  series-nw:
    driver: bridge
